### ISSUE TITLE
Dismiss all toasts created by Materialize.toast(...) programatically

### ISSUE THREAD

**Issue by ancientdemon** [xrexonx/Laravel-Materialize#2]
Hello,

In my single page app, I want to dismiss all toasts displayed to the user when page navigation happens. Basically what I am looking for is a Materialize.toast.dismissAll() kind of method. I searched and looked for help but could not figure out a legitimate way to do this (discounting the hacks). Is there a way to do this, and if not, I would like to propose a feature that allows this.

Thanks

**Comment by ancientdemon** [comment]
sorry! wrong repository, I am closing this issue since I don't see a way to delete it. I am sorry

**Comment by xrexonx** [comment]
Hehe.. It's okay.. :+1:
